dist: trusty
#
#language: java

jdk:
  - oraclejdk11

# https://docs.travis-ci.com/user/sonarcloud/

addons:
  sonarcloud:
    organization: "speech4j"
    token:
      secure: "MMwXWiwmPEF4b+d0BwPoCtc1LykU6yjTMTeuc0CoX27Mxn9SqsenSwKcWUWbO5hzlYOTsqpGCR7PhSLkhX85u1tQEgGGSwhS9iOy6zfNq8DMQ+FvJHPZz43Othrul235bz/qzI/ryelEj+NOACksk/Ib4jTrreUHIm7A7or2GC6oqi0NBhA1QV9lFsUzFGpOk77NVRvuhHqNRYqqmskONoglky0NoQqBIAKeP1TIvEngjfY+FXEolpuudOm+Y/Fc77tuMhjLOVB9rLfPv4WhIRkAkd4wUDfY+zGyMiOPCZcHFMjWNeT31Z2XOMeVl17JlVsypxlboIknnkVWMfXKEmLC2qec7KGKYPNMa6eLg6yWO8/TSXBB27YwPfrkPe+34wo+q7wme/QriREy7TicqnPF9ADHYgfWnIp6ELGGLZcSDH4HTvcC6woIrq30MIywFsoZ1T0gdteCNgA80rAu/XrQMiyrYjVxrPnXQbzBd0Yc0DnyTUo24Rfff+ApmmssHCegT6YTK0RthG95vj4k3KTNBCULA4tRMWmgdYOa7d+MYUZOwYeV5V9d/19xLNr5ZMSxo6kQeDBwrUAMhJUFKmqXwN2SIo1RRfQYlptd0lB9mEbtZPCOB1ie6Tzhkuu/L+ZW9VwSaalxZpqkMissD/LyZJEqL7RZcbfFGfhxt/4="

before_install:
  - chmod +x gradlew

script:
#  - ./gradlew sonarqube
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "./build/customJacocoReportDir/codeCoverageReport/codeCoverageReport.xml"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

# https://adamweidner.com/posts/sonar-with-gradle-submodules/
# https://sonarcloud.io/dashboard?id=speech4j_speech4j
# https://github.com/SonarSource/sq-com_example_java-gradle-travis/blob/master/.travis.yml
# https://testdriven.io/blog/getting-telegram-notifications-from-travis-ci/
# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
# https://medium.com/@proustibat/using-sonarcloud-with-travis-ci-to-measure-and-continuously-improve-code-quality-5ea7fb5a587b
# https://asus-aics.github.io/DeveloperGuide/pages/020_sonar_cloud/