dist: trusty
#
#language: java

jdk:
  - oraclejdk11

# https://docs.travis-ci.com/user/sonarcloud/

addons:
  sonarcloud:
    organization: "speech4j"
    token:
      secure: "QHBjBgA0heWnsAgtD4nB5ETvv3SIB0Ij+LiCxYnaa/sOAgo3/ews0fPCHdzD1rxm7gZOn878FRypd2BZIt6F+5sQD1gLi3EN6reloZDA1orIK7qfmUPmA+4XoFg7g1CHgNw6EpDbgfb2X/rmQXGZ4IPqM1qahf1ypTGljFkfP+gPlkcG/yGo9BglOK9WXWZQT2GQAA4Xo3IJGajxBiFxCYJ40TdFHQkhluRt/tXaqb/yZax0r/jznVRhwwj1NJ5BiuqhbD+XO51oUxlB9vBLwrjHY/Cbgpzn6fV66FzOk7605X56tNFhD4gYfiPN35tZfjznGZB83mzlcxiC9KxKiKsCG/kylpRNL91PLiifk9SeN2FHHgBCsyLsixfnyPVBPy09ogu2WskCPYb3vrXqcbXcL1jRmjWrGLfHq2PPsQHa7AM9xOE7cO2XrEQSozHXkbZ1u3r5yEXIfSMRccxhlqX5UPW9tTxOF7nwM+gz3JW8EPCu0eLX0eWqQrHxX7RTZgxOqswVxOvk39moCRM06P/7RmY9KNN6E6sqswMAEpiuvh1aiIVPiblnvpH0O/U/IYCjYfcsvgWAldk8Fx9YiWIOd/TpQWiK4B3Cai+u4XhTVJBONqm1fBBpJU3ZRLtZIYEWs2OgHPt5ZFl4QMc1t5mvtq9Ss26oRi+65vxOJBo="

before_install:
  - chmod +x gradlew

script:
  - ./gradlew sonarqube
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "./build/customJacocoReportDir/codeCoverageReport/codeCoverageReport.xml"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

# https://adamweidner.com/posts/sonar-with-gradle-submodules/
# https://sonarcloud.io/dashboard?id=speech4j_speech4j
# https://github.com/SonarSource/sq-com_example_java-gradle-travis/blob/master/.travis.yml
# https://testdriven.io/blog/getting-telegram-notifications-from-travis-ci/
# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
# https://medium.com/@proustibat/using-sonarcloud-with-travis-ci-to-measure-and-continuously-improve-code-quality-5ea7fb5a587b
# https://asus-aics.github.io/DeveloperGuide/pages/020_sonar_cloud/