dist: trusty
#
#language: java

jdk:
  - oraclejdk11

# https://docs.travis-ci.com/user/sonarcloud/

addons:
  sonarcloud:
    organization: "speech4j"
    token:
      secure: "HHA0Xp89FNjJVvUFw/cwF0TyUJUmbIEi7jHBzNDMDC3dTaJnJfPMSPRoW/CU7I9JOfLmFaCe54jDLDJYVXBW38woVS34j2AyF3JFX0hXYm0HpGXvYS7ZdxJssAo1Udl2E/imi0D3nNwhwdJK7tvoSvEpAUjHjNCG/FIwYDKc0geaRXlJQp3vHeTDNub7BOQNPW3YJc73WlNYJjdMJ4LGkWDRYehrGI2PX9rlaQ1wb0eMB5Le32yo6+jyEWUWfIJGk93wCAnm1bdfDPEqyqn95xearBLdRhRJoiVA7yWO1kIl/oM3DMqFYvCln3ovKDsaBOtb7KYa4dd9Iz2cr38ZJmkO/73KhSeuxCCRZKUkC5+iigQ03118PjJ34++8oi3tEpKyfgBv4kk1/v2uwphyalYV0/krA2BNNXGKrhssz+r3yuIdhidkB6UdN6mAGy+3XWJz4oc2Nqg0zhEeN2hW/xykReRd8fcMB0qKADYJNPzFXWl2gVdKZo7N0axQT9qkr4JIl325mpBmnrRHrPyVI57SR6V3wFMRhX7sry+s6Cl9yGelihQz/K+GCO/xOvc+k9jCStK4/WnwkzUd8N6AmUWuZbAo7GWnNWcGJHTvos6rxkUStwY9jDZSrCS9hyhEyfNbDaGJzwbsrHY5YhhkrXNR1mkYNB8gnEIPqun0lUs="

before_install:
  - chmod +x gradlew

script:
  - ./gradlew sonarqube
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "./build/customJacocoReportDir/codeCoverageReport/codeCoverageReport.xml"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

# https://adamweidner.com/posts/sonar-with-gradle-submodules/
# https://sonarcloud.io/dashboard?id=speech4j_speech4j
# https://github.com/SonarSource/sq-com_example_java-gradle-travis/blob/master/.travis.yml
# https://testdriven.io/blog/getting-telegram-notifications-from-travis-ci/
# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
# https://medium.com/@proustibat/using-sonarcloud-with-travis-ci-to-measure-and-continuously-improve-code-quality-5ea7fb5a587b
# https://asus-aics.github.io/DeveloperGuide/pages/020_sonar_cloud/