dist: trusty
#
#language: java

jdk:
  - oraclejdk11

# https://docs.travis-ci.com/user/sonarcloud/

addons:
  sonarcloud:
    organization: "speech4j"
    token:
      secure: "ZuwOQ9hHD4TbuvHStTTzewOTnCps66wtSuhFDXCbB3LrrqhyRrtNovr43H/IfaX8NwPydI7e7NTs09durkIO0ouvxJm/NjExMxGO2zWNpsjVcwt8pmh/7uFxHMlGFCsi9M7aAXR2m/RfHqv6Qc/Pg3wTNvVPAltAfISt06n4PW0votrHXj3u5QPkWFv1aNGNehOWXMdZMvIXUmlRxUZjObPcri6FyUoa6nNOc0ZVmHsDIGAKiPV7WtoRanosayz0ZLmtOs8+L+AX/h8Pu8jzHr9fRWqo9f6uodgjQDLVCODfUri7OvuW2FdxWAzr6IkeuQTM5g0UTzoBxD4mgQCX08atn9KZkeIqapuzebNuYiQTNn7dxemwtwcqRVR3Wcz2WMsfWMzTx9zWDfHYzA6GptK24uHUHzMKD5x8wo13Nkd/jyErGg1B5ovTEiZS+KTbcfGZXPorl5uL4q9UyPFfChRHLAjrmpf+oTfkj9pf5OCYPjPkski0kO6eZCESLdXXCzAEXSQNolKRkoKPCv82rA3zU40yaPo33Kmsa7Ykc/9WDVRtaCh2v3bXMeDpzWnGQkmAqFL3xIM02CFlCq/bfpYCi/ucn76t1uInSf+XunXym6n0Xvc3vF8z4S/KkC+gimWSgDowMVJkKE9pmRdYNhUp3Y1WJAePfZrjyg4BRXo="

before_install:
  - chmod +x gradlew

script:
  - ./gradlew sonarqube
#  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "./build/customJacocoReportDir/codeCoverageReport/codeCoverageReport.xml"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

# https://adamweidner.com/posts/sonar-with-gradle-submodules/
# https://sonarcloud.io/dashboard?id=speech4j_speech4j
# https://github.com/SonarSource/sq-com_example_java-gradle-travis/blob/master/.travis.yml
# https://testdriven.io/blog/getting-telegram-notifications-from-travis-ci/
# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
# https://medium.com/@proustibat/using-sonarcloud-with-travis-ci-to-measure-and-continuously-improve-code-quality-5ea7fb5a587b
# https://asus-aics.github.io/DeveloperGuide/pages/020_sonar_cloud/